CREATE TABLE DEPT(
 DEPTNO              int NOT NULL,
 DNAME               VARCHAR(14),
 LOC                 VARCHAR(13),
 CONSTRAINT DEPT_PRIMARY_KEY PRIMARY KEY (DEPTNO));

INSERT INTO DEPT VALUES (10,'ACCOUNTING','NEW YORK');
INSERT INTO DEPT VALUES (20,'RESEARCH','DALLAS');
INSERT INTO DEPT VALUES (30,'SALES','CHICAGO');
INSERT INTO DEPT VALUES (40,'OPERATIONS','BOSTON');

CREATE TABLE EMP (
 EMPNO               int NOT NULL,
 ENAME               VARCHAR(10),
 JOB                 VARCHAR(9),
 MGR                 int CONSTRAINT EMP_SELF_KEY REFERENCES EMP (EMPNO),
 HIREDATE            DATE,
 SAL                 int,
 COMM                int,
 DEPTNO              int NOT NULL,
 CONSTRAINT EMP_FOREIGN_KEY FOREIGN KEY (DEPTNO) REFERENCES DEPT (DEPTNO),
 CONSTRAINT EMP_PRIMARY_KEY PRIMARY KEY (EMPNO));

INSERT INTO EMP VALUES (7839,'KING','PRESIDENT',NULL,'17-NOV-81',5000,NULL,10);
INSERT INTO EMP VALUES (7698,'BLAKE','MANAGER',7839,'1-MAY-81',2850,NULL,30);
INSERT INTO EMP VALUES (7782,'CLARK','MANAGER',7839,'9-JUN-81',2450,NULL,10);
INSERT INTO EMP VALUES (7566,'JONES','MANAGER',7839,'2-APR-81',2975,NULL,20);
INSERT INTO EMP VALUES (7654,'MARTIN','SALESMAN',7698,'28-SEP-81',1250,1400,30);
INSERT INTO EMP VALUES (7499,'ALLEN','SALESMAN',7698,'20-FEB-81',1600,300,30);
INSERT INTO EMP VALUES (7844,'TURNER','SALESMAN',7698,'8-SEP-81',1500,0,30);
INSERT INTO EMP VALUES (7900,'JAMES','CLERK',7698,'3-DEC-81',950,NULL,30);
INSERT INTO EMP VALUES (7521,'WARD','SALESMAN',7698,'22-FEB-81',1250,500,30);
INSERT INTO EMP VALUES (7902,'FORD','ANALYST',7566,'3-DEC-81',3000,NULL,20);
INSERT INTO EMP VALUES (7369,'SMITH','CLERK',7902,'17-DEC-80',800,NULL,20);
INSERT INTO EMP VALUES (7788,'SCOTT','ANALYST',7566,'09-DEC-82',3000,NULL,20);
INSERT INTO EMP VALUES (7876,'ADAMS','CLERK',7788,'12-JAN-83',1100,NULL,20);
INSERT INTO EMP VALUES (7934,'MILLER','CLERK',7782,'23-JAN-82',1300,NULL,10);
/*1*/
SELECT ename,sal,deptno,job,mgr,hiredate,comm,empno
FROM emp
WHERE  job LIKE 'C%K';
/*2*/
SELECT ename,sal,deptno,job,mgr,hiredate,comm,empno
FROM emp
WHERE  job ='CLERK' OR job='MANAGER';
/*3*/
SELECT GETDATE();
/*4*/
SELECT ename,sal,comm,deptno
FROM emp
WHERE sal BETWEEN 500 AND 1000;
/*5*/
SELECT HIREDATE,ENAME
FROM emp
WHERE HIREDATE  LIKE '____-12-%'
/*6*/
SELECT ename,sal,comm,deptno
FROM emp
WHERE  sal   NOT BETWEEN 1000 AND 2500
ORDER BY sal;
/*7*/
SELECT ename,sal,comm,deptno
FROM emp
WHERE  sal IN (800,950,3000,5000);
/*8*/
SELECT ename,sal,comm,deptno
FROM emp
WHERE ename LIKE '_L%';
/*9*/
SELECT ename,sal,comm,deptno
FROM emp
WHERE ename LIKE '%D';
/*11*/
SELECT ename,sal,comm,deptno
FROM emp
WHERE ename LIKE 'T%R';
/*12*/
SELECT ename,sal,comm,deptno
FROM emp
WHERE ename LIKE '%A%';
/*14*/
SELECT EMPNO,ENAME
FROM emp
WHERE ename='JAMES';
/*15*/
SELECT sal,ename
FROM emp
WHERE ename='KING';
/*16*/
SELECT ENAME,JOB
FROM emp
WHERE JOB='PRESIDENT';
/*17*/
SELECT ENAME,JOB,SAL,COMM,EMPNO,MGR
FROM emp
WHERE JOB='MANAGER';
/*18*/
SELECT *
FROM EMP
WHERE COMM IS NOT NULL
/*22*/
SELECT ENAME,SAL
FROM EMP
WHERE SAL<3500;
/*23*/
SELECT ENAME,SAL,EMPNO,COMM,JOB,MGR
FROM EMP
WHERE JOB LIKE 'C%K';
/*24*/
SELECT ENAME,EMPNO,COMM,JOB,MGR,
SAL/30 AS 'ANNUAL SALARY'
FROM EMP
/*26*/
select deptno,sum(sal) as Maxsalary
from emp
Group by deptno
/*27*/
SELECT DEPTNO,MIN(SAL) AS 'LOWEST SALARY'
FROM EMP DEPT
WHERE DEPTNO=10
GROUP BY DEPTNO
/*28*/
AVG(sal) AS 'Average'
FROM emp
WHERE job='manager'
GROUP BY  job
/*29*/
SELECT  sum(sal) AS 'totalsalary'
FROM emp
WHERE job='salesman'
GROUP BY  job
/*30*/
SELECT DEPTNO,AVG(SAL) AS'LOWEST AVG SALARY'
FROM EMP
GROUP BY DEPTNO
HAVING AVG(SAL)<(SELECT AVG(SAL) FROM EMP);
/*31*/
SELECT JOB,COUNT(*) AS 'PERSONS'
FROM EMP
GROUP BY JOB
/*32*/
SELECT  
max(sal),ename
FROM emp
WHERE job='analyst'
GROUP BY  job,ename
/*35*/
SELECT ENAME
FROM EMP
WHERE ENAME LIKE '__L%';
/*25*/
SELECT ENAME,SAL+(SAL*20/100) AS'MONTHLY HIKE',(SAL+(SAL*20/100))*12 AS 'ANNUAL SALARY'
FROM EMP
WHERE ENAME='FORD';
/*10*/
SELECT ENAME
FROM EMP
WHERE DATALENGTH(ENAME)=5;










